package youtube

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"testing"
	"time"
)

func TestIntegration_YouTubeLifecycle(t *testing.T) {
	token := os.Getenv("YOUTUBE_TEST_TOKEN")
	if token == "" {
		t.Skip("Skipping integration test: YOUTUBE_TEST_TOKEN is not set")
	}

	videoPath := "testdata/sample.mp4"
	videoFile, err := os.Open(videoPath)
	if err != nil {
		t.Skipf("Skipping integration test: could not open %s: %v", videoPath, err)
	}
	defer videoFile.Close()

	cfg := YouTubeConfig{
		ClientID:    "test",
		ClientSecret: "test", 
		CallbackURL: "test",
	}

	conn := New(cfg)
	conn.SetAccessToken(token)

	ctx := context.Background()

	t.Log("1. Uploading media...")
	mediaID, err := conn.UploadMedia(ctx, token, videoFile, "video/mp4")
	if err != nil {
		t.Fatalf("UploadMedia failed: %v", err)
	}
	t.Logf("Uploaded video ID: %s", mediaID)

	t.Log("2. Publishing video metadata...")
	caption := "[Test] Automated Upload\nThis is a private test upload generated by integration testing."
	publicURL, platformPostID, err := conn.Publish(ctx, token, caption, mediaID)
	if err != nil {
		t.Fatalf("Publish failed: %v", err)
	}
	t.Logf("Video published at: %s (ID: %s)", publicURL, platformPostID)

	if mediaID != platformPostID {
		t.Errorf("Expected platformPostID %s to match mediaID %s", platformPostID, mediaID)
	}

	t.Log("3. Polling video status...")
	maxAttempts := 5
	for i := 0; i < maxAttempts; i++ {
		status, _, err := conn.GetStatus(ctx, mediaID)
		if err != nil {
			t.Fatalf("GetStatus failed: %v", err)
		}
		t.Logf("Status attempt %d: %s", i+1, status)
		
		if status == "published" || status == "failed" {
			break
		}
		time.Sleep(5 * time.Second)
	}

	t.Log("4. Cleaning up test video...")
	deleteURL := fmt.Sprintf("%s/videos?id=%s", "https://www.googleapis.com/youtube/v3", mediaID)
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, deleteURL, nil)
	if err == nil {
		req.Header.Set("Authorization", "Bearer "+token)
		resp, err := http.DefaultClient.Do(req)
		if err == nil {
			defer resp.Body.Close()
			if resp.StatusCode == http.StatusNoContent {
				t.Log("Video successfully deleted.")
			} else {
				t.Logf("Failed to delete video, status code: %d", resp.StatusCode)
			}
		}
	}
}
